version: "3"

services:
  app:
    container_name: pokemon-game-help
    build:
      dockerfile: ./docker/Dockerfile
      context: .
    ports:
      - 3333:3333
    environment:
      NODE_ENV: development
      NODE_PORT: 3333
    command: npm run dev
    volumes:
      - .:/app/
      - /app//node_modules
    depends_on:
      - database


  database:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
