const swaggerAutogen = require('swagger-autogen')()

const outputFile = './swagger_output.json'
const endpointsFiles = ['./src/routes/Index.js']

const port = process.env.PORT || 3333

const doc = {
  info: {
    version: '1.0.0',
    title: 'PokemonGameHelpAPI',
    description: 'Documentation automatically generated by the <b>swagger-autogen</b> module.'
  },
  host: `localhost:${port}`,
  basePath: '/',
  schemes: ['http', 'https'],
  consumes: ['application/json'],
  produces: ['application/json']
}

swaggerAutogen(outputFile, endpointsFiles, doc)
